<a href="https://colab.research.google.com/github/300201754/Python-3/blob/master/DAYml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!cal

    January 2020      
Su Mo Tu We Th Fr Sa  
          1  2  3  4  
 5  6  7  8  9 10 11  
12 13 14 15 16 17 18  
19 20 21 22 23 24 25  
26 27 28 29 30 31     
                      


In [0]:
! cat /etc/issue


Ubuntu 18.04.3 LTS \n \l



In [0]:
# pip install numpy
# for using array we will numpy
import numpy as np
#[i for i in dir(np) if 'arr' in i]


['array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'broadcast_arrays',
 'chararray',
 'compare_chararrays',
 'get_array_wrap',
 'ndarray',
 'numarray',
 'recarray']

In [0]:
# to search in python modules
x=np.array([1,2,3,4])
y=np.array([12,34,45,65,456])
x

array([1, 2, 3, 4])

In [0]:
# to check data type of this
type(x)

numpy.ndarray

In [0]:
# TO add same Dimension array
# x+Y

In [0]:
x*3


array([ 3,  6,  9, 12])

In [0]:
# TIME FOR 2d array
a=np.array([[2,3,4],[5,6,7],[4,6,78],[5,6,7,8]])
a

array([list([2, 3, 4]), list([5, 6, 7]), list([4, 6, 78]),
       list([5, 6, 7, 8])], dtype=object)

In [0]:
 # TO CHECK dim
 a.shape

(4,)

In [0]:
# to print 1st row
a[0]

[2, 3, 4]

In [0]:
# first element of array
a[0][0]

2

In [0]:
# first two row
a[0:2]

array([list([2, 3, 4]), list([5, 6, 7])], dtype=object)

In [0]:
# first two row we call it range in python 
a[0:,0] 

IndexError: ignored

In [0]:
# random array
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones((10,13))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
np.full((10,15),6)

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])